stages:
  - test
  - deploy
test:
  image: julia:1.5
  stage: test
  before_script:
  - julia -e "using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()"
  script:
  - julia --project -e "using Pkg; Pkg.test(; coverage=true)"
pages:
  image: julia:1.5
  stage: deploy
  dependencies:
  - test
  only:
  - documentation
  - staging
  - tags
  - master
  before_script:
  - julia --project=docs/ -e "using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()"
  script:
  - julia --project=docs/ --code-coverage=user docs/make.jl
  after_script:
  - mkdir -p public
  - cp -R docs/build/* public
  artifacts:
    expire_in: 10 days
    paths:
    - docs/build
    - public
